'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [
      {
        name: 'marcos',
        surname: 'altamirano',
        email: 'marcosaltamirano023@hotmail.com',
        password: 'admin123',
        phone: '2266479627',
        address: 'ramon sorondo 483',
        city: 'balcarce',
        postalCode: '7620',
        isAdmin: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'pepe',
        surname: 'gomez',
        email: 'pepe@example.com',
        password: '123456',
        phone: '1234567890',
        address: 'Calle Falsa 123',
        city: 'Ciudad Ejemplo',
        postalCode: '12345',
        isAdmin: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'joselito',
        surname: 'martinez',
        email: 'joselito@example.com',
        password: '123456',
        phone: '1234567890',
        address: 'Calle Falsa 123',
        city: 'Ciudad Ejemplo',
        postalCode: '12345',
        isAdmin: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'paquito',
        surname: 'diaz',
        email: 'paquito@example.com',
        password: '123456',
        phone: '1234567890',
        address: 'Calle Falsa 123',
        city: 'Ciudad Ejemplo',
        postalCode: '12345',
        isAdmin: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'pablo',
        surname: 'gonzalez',
        email: 'pablo@example.com',
        password: '123456',
        phone: '1234567890',
        address: 'Calle Falsa 123',
        city: 'Ciudad Ejemplo',
        postalCode: '12345',
        isAdmin: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Juancho',
        surname: 'sain',
        email: 'juancho@example.com',
        password: '123456',
        phone: '1234567890',
        address: 'Calle Falsa 123',
        city: 'Ciudad Ejemplo',
        postalCode: '12345',
        isAdmin: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'matias',
        surname: 'jauncito',
        email: 'matias@example.com',
        password: '123456',
        phone: '1234567890',
        address: 'Calle Falsa 123',
        city: 'Ciudad Ejemplo',
        postalCode: '12345',
        isAdmin: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'manolo',
        surname: 'jose',
        email: 'manolo@example.com',
        password: '123456',
        phone: '1234567890',
        address: 'Calle Falsa 123',
        city: 'Ciudad Ejemplo',
        postalCode: '12345',
        isAdmin: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Juan',
        surname: 'Pérez',
        email: 'juan@example.com',
        password: '123456',
        phone: '1234567890',
        address: 'Calle Falsa 123',
        city: 'Ciudad Ejemplo',
        postalCode: '12345',
        isAdmin: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};

